### ISSUE TITLE
Please fix issues in CRAN

### ISSUE THREAD

**Issue by eliocamp** [decisionpatterns/sticky#11]
Hi! Another package mantainer and I receive a notice that this package has not fixed some outstanding problems (seen [here](https://cran.r-project.org/web/checks/check_results_sticky.html)) and thus it is scheduled for archival two weeks from now. This would force our packages to be archived too. 

Please, can you fix this issue? If you're not able, I volunteer myself to become maintainer.

**Comment by ctbrown** [comment]
Fixed will push to CRAN this AM.

**Comment by eliocamp** [comment]
Awesome! Thanks!

**Comment by ctbrown** [comment]
Accepted to CRAN.
