### ISSUE TITLE
please please push to CRAN!

### ISSUE THREAD

**Issue by maxheld83** [decisionpatterns/sticky#8]
your package is a godsend! Thanks so much, really saved my ass here!

Any chance you might push >= 0.5.3 to CRAN sometime soon?

I'm using sticky in my package, and am using multiple classes, so relying on >= 0.5.3.

And, of course, CRAN, won't allow dependencies from github ...

Thanks for the generous work!

**Comment by ctbrown** [comment]
Pushing.
